USE [IUL]
GO

/****** Object:  Table [dbo].[CHAPTERS]    Script Date: 11.04.2022 18:07:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHAPTERS](
	[CHAPTER_ID] [nchar](60) NOT NULL,
	[CHAPTER_PROJECT_ID] [nchar](40) NOT NULL,
	[CHAPTER_NAME] [text] NOT NULL,
	[CHAPTER_FILE_NAME] [text] NOT NULL,
 CONSTRAINT [PK_CHAPTERS] PRIMARY KEY CLUSTERED 
(
	[CHAPTER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[CHAPTERS]  WITH CHECK ADD  CONSTRAINT [FK_CHAPTERS_PROJECTS] FOREIGN KEY([CHAPTER_PROJECT_ID])
REFERENCES [dbo].[PROJECTS] ([PROJECT_ID])
GO

ALTER TABLE [dbo].[CHAPTERS] CHECK CONSTRAINT [FK_CHAPTERS_PROJECTS]
GO

USE [IUL]
GO

/****** Object:  Table [dbo].[EMPLOYEES]    Script Date: 11.04.2022 18:09:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLOYEES](
	[EMPLOYEE_ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_SURNAME] [nchar](30) NOT NULL,
	[EMPLOYEE_NAME] [nchar](30) NOT NULL,
	[EMPLOYEE_PATROMIC] [nchar](30) NULL,
	[EMPLOYEE_SIGN] [image] NOT NULL,
 CONSTRAINT [PK_EMPLOYEES] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [IUL]
GO

/****** Object:  Table [dbo].[PERFORMERS]    Script Date: 11.04.2022 18:09:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PERFORMERS](
	[PERFORMER_ID] [int] IDENTITY(1,1) NOT NULL,
	[PERFORMER_CHAPTER_ID] [nchar](60) NOT NULL,
	[PERFORMER_EMPLOYEE_ID] [int] NOT NULL,
	[PERFORMER_ROLE_ID] [int] NOT NULL,
 CONSTRAINT [PK_PERFORMERS] PRIMARY KEY CLUSTERED 
(
	[PERFORMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PERFORMERS]  WITH CHECK ADD  CONSTRAINT [FK_PERFORMERS_CHAPTERS] FOREIGN KEY([PERFORMER_CHAPTER_ID])
REFERENCES [dbo].[CHAPTERS] ([CHAPTER_ID])
GO

ALTER TABLE [dbo].[PERFORMERS] CHECK CONSTRAINT [FK_PERFORMERS_CHAPTERS]
GO

ALTER TABLE [dbo].[PERFORMERS]  WITH CHECK ADD  CONSTRAINT [FK_PERFORMERS_EMPLOYEES] FOREIGN KEY([PERFORMER_EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID])
GO

ALTER TABLE [dbo].[PERFORMERS] CHECK CONSTRAINT [FK_PERFORMERS_EMPLOYEES]
GO

ALTER TABLE [dbo].[PERFORMERS]  WITH CHECK ADD  CONSTRAINT [FK_PERFORMERS_ROLES] FOREIGN KEY([PERFORMER_ROLE_ID])
REFERENCES [dbo].[ROLES] ([ROLE_ID])
GO

ALTER TABLE [dbo].[PERFORMERS] CHECK CONSTRAINT [FK_PERFORMERS_ROLES]
GO

USE [IUL]
GO

/****** Object:  Table [dbo].[PROJECTS]    Script Date: 11.04.2022 18:09:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROJECTS](
	[PROJECT_ID] [nchar](40) NOT NULL,
	[PROJECT_NAME] [text] NOT NULL,
	[PROJECT_CAPITAL_OR_LINEAR] [bit] NOT NULL,
	[PROJECT_GEODETI_SURVEYS] [bit] NOT NULL,
	[PROJECT_GEOLOGICAL_SURVEYS_SURVEYS] [bit] NOT NULL,
	[PROJECT_ENVIRONMENTAL_SURVEYS] [bit] NOT NULL,
	[PROJECT_METEOROLOGICAL_SURVEYS] [bit] NOT NULL,
	[PROJECT_GEOTECHNICAL_SURVEYS] [bit] NOT NULL,
	[PROJECT_ARCHAEOLOGICAL_SURVEYS] [bit] NOT NULL,
	[PROJECT_INSPECTION_OF_TECHNICAL_CONDITION] [bit] NOT NULL,
	[PROJECT_CUSTOMER] [text] NOT NULL,
	[PROJECT_GIP_ID] [int] NOT NULL,
	[PROJECT_N_KONTR_ID] [int] NOT NULL,
	[PROJECT_PATH_FOLDER] [text] NOT NULL,
 CONSTRAINT [PK_PROJECTS] PRIMARY KEY CLUSTERED 
(
	[PROJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROJECTS]  WITH CHECK ADD  CONSTRAINT [FK_PROJECTS_EMPLOYEES] FOREIGN KEY([PROJECT_N_KONTR_ID])
REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID])
GO

ALTER TABLE [dbo].[PROJECTS] CHECK CONSTRAINT [FK_PROJECTS_EMPLOYEES]
GO

ALTER TABLE [dbo].[PROJECTS]  WITH CHECK ADD  CONSTRAINT [FK_PROJECTS_EMPLOYEES1] FOREIGN KEY([PROJECT_GIP_ID])
REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEE_ID])
GO

ALTER TABLE [dbo].[PROJECTS] CHECK CONSTRAINT [FK_PROJECTS_EMPLOYEES1]
GO

USE [IUL]
GO

/****** Object:  Table [dbo].[ROLES]    Script Date: 11.04.2022 18:09:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ROLES](
	[ROLE_ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_FULL_NAME] [nchar](30) NOT NULL,
	[ROLE_ABBREVIATED_NAME] [nchar](20) NOT NULL,
 CONSTRAINT [PK_ROLES] PRIMARY KEY CLUSTERED 
(
	[ROLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO