USE IUL;
SELECT 
[IUL].[dbo].[CHAPTERS].[CHAPTER_NAME] AS 'Наименование раздела',
[IUL].[dbo].[EMPLOYEES].[EMPLOYEE_FNAME] AS 'Фамилия исполнителя',
[IUL].[dbo].[ROLES].[ROLE_ABBREVIATED _NAME] AS 'Роль исполнителя'
FROM
[IUL].[dbo].[PERFORMERS]
JOIN [IUL].[dbo].[CHAPTERS]
ON [IUL].[dbo].[PERFORMERS].[PERFORMER_CHAPTER_ID] = [IUL].[dbo].[CHAPTERS].[CHAPTER_ID]
JOIN [IUL].[dbo].[EMPLOYEES]
ON [IUL].[dbo].[PERFORMERS].[PERFORMER_EMPLOYEE_ID] = [IUL].[dbo].[EMPLOYEES].[EMPLOYEE_ID]
JOIN [IUL].[dbo].[ROLES]
ON [IUL].[dbo].[PERFORMERS].[PERFORMER_ROLE_ID] = [IUL].[dbo].[ROLES].[ROLE_ID]
WHERE [IUL].[dbo].[PERFORMERS].[PERFORMER_CHAPTER_ID] LIKE '%КР_%_%';
